app = "crypto-strength-vs-btc-live"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["webapp"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/"
    protocol = "http"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["worker"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[processes]
  webapp = "/app/start.sh webapp"
  worker = "/app/start.sh worker" 