app = "crypto-strength-vs-btc-backend-worker"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["worker"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[processes]
  worker = "/app/start.sh worker" 